name: Mmorpg
version: 0.1.1a
author: jamailun
main: fr.jamailun.Mmorpg.Main
depend: [ArmorEquipEvent]
solftdepend: [ProtocolLib]
commands:
  mmorpg:
    usage: /mmorpg <commande>
    description: L'ensemble des commandes du plugin mmorpg.
